sudo: required
services:
- docker
env:
  global:
  - REPO: shazi7804/apache2-fastcgi-worker-php7
  matrix:
  - PHP_VERSION=7.0
  - PHP_VERSION=7.1
script:
- travis_retry docker build -t ${REPO}:${PHP_VERSION} ${PHP_VERSION}/.
- docker run -itd --name=docker ${REPO}:${PHP_VERSION}
- docker exec docker bash -c "echo '<?php phpinfo(); ?>' >> /var/www/html/index.php"
- docker exec docker bash -c "curl http://localhost"
notifications:
  email: false
  slack:
    secure: 5mgrA3hInrn3CGdvg1HuItcL27niO4dWswLMZ/1x2fYUea1Z8OyweAuL8mKeuepLUVsvLbll3fXePE477OXJ9TNdxq28bVmv5FaN51Hhdx0WEEcoHlbWeFbG7SRk0ejMb+D3gohIIOGZFzyhFi4s0pG6+IkhEIZCOO9jZa5ZuKZ0arY99jIkXTo9bVi41RNX40cIMfjv0NhrQoMlzxcSRVGRNBx/tWDthaTK/lAnvlIkb2vbQHinUcrvDv6fC5btQ2Uchx/ZLDvFi6s6BZpB+YNzjeq6qyNYqLAUaRvRcBBZkT30nb6ise7xtiFgOvQL4fcVRYVQO2m2GID33mtJ334VP1Og8XgCOslg8vgo1Un32M0mP3Ot7ymuZQlEpn/W2NbXbjMVruZCmeTVzCS7P40jG8CkCbnKl+IMDt70qyqsp2AaQVlpJc8Apz/nFQHXmVSBraCCLiqON1beC6G38N+md8jMaQsyu98SNPiN3HU97WO3D9bqdKMlE0m7rO3G3TdM9E3DIHqNUK9YEMNUn469pWToiSMiWE+hugtR6vIXyrdZzVDuZimVwnOmtAVOEW6rdc9kGcxrgnDTvuervHBskNsF1T6GjLJNc1ZSkSGsXyZoNDlPvpa/QBCs0gfImLB8KT42aW3rb2WbJ+4ZqopAyVjB+Zqiy0ugoPrnw40=
    rooms:
      secure: ZHAXsfAT2+zNzUEq0hIVJzcREyFDa0MxVl9zc56VH6Uv4dAhI/vVlFkjItFvCqt8FhB3F+ZTdhmWU2H574TnicGTRBLNsx+OnZDTtgW9tlZnlsUPuxwf08DcHIrHTkMAfY5pYZRDuDHER8d4dcdj2+6oIyt2KVDw/RNW2JBJWRD7hgV8L4QpW6WEciR+Y4JkER7Obo9sivbzuXtyZIvYcmoTJt2/yJ7/j+I5PSB/D088osZKaP3qXfJcZ2Gq6PINT10WV/mLihWoM8GgGdqX7gpvs8R+J93+i0c5hAqWiS7FqmzHy/Pvz3f5iDqAcpEupNUmhmpnovGqYYSI4vBljZzmpR7on1W9vPD8cHO7dGn6JRhVYzl0xKKhO/XHyQPscTOt+mUk1pgRNpsqXBJnArhSf4aKdExo56g8SWy5UW7Um5jqtDBsNsj57dHhYJyeRpWuN6cePP7i7NCeohhVEbg0Uu7XKDkxoLe9NpcGxwIhjpUAyB5X9wDYMTZSvD2ity+MLcitcSAyaiUsmaf2kdBhh69CO70KcQzF+DhG43MUXvSxlucSdmKTkIGD9VVeJUkbPi12NZKszM+UtRa97D8a0hjbWWlOEa6iVqB7AcE2AHO8C0U4jzPo8FJ2YkbTTj4DH/YZwYQ1kzgj3oDwxdvv/M2dWw8q4yDo6/Puq0k=
