sudo: required
services:
- docker
env:
  global:
  - REPO: shazi7804/apache2-fastcgi-worker-php7
  matrix:
  - PHP_VERSION=7.0
  - PHP_VERSION=7.1
script:
- travis_retry docker build -t ${REPO}:${PHP_VERSION} ${PHP_VERSION}/.
- docker run -itd --name=docker ${REPO}:${PHP_VERSION}
- docker exec docker bash -c "echo '<?php phpinfo(); ?>' >> /var/www/html/index.php"
- docker exec docker bash -c "curl http://localhost"
notifications:
  email: false
  slack:
    rooms:
      secure: MOO20Km7NVbqZ8NmmfHUMmXUDKHG4wsIvy2o00FgQ1Rq3Cv7Fs+ncAusArvH4xAqC/2ZvNz82IJhmcGIHHcfW5VjqHMHbqgYZ+gdW9TY86Z+F0YpQooHL69ywmqq1cHqK5StKxcXvNg4S/vLRtliQtnrED/LkivTje59TIf4pJ+9ZH1vvOYafK6266/tAWhxYsfRJGunGfcPtUqRUQJXXhxiUNr8d9Br6Yi6ZQLqJWSpqbWvnHk/CXhdf+ze2ZI67uxEPdSB4eKxXYwOXi6ep4hJIosoJGow537fmKUOjRHsy2bhot33auSilagMQBvL6vYa6wJ8d2bGTDNJ+XlaMizrjpKXLa3KtxnFn3elsjJOQo52jEx69FU7zKKw0roPBQSHyL571J/ahT4L+uKm4K0uW7CT9VoiGLyjdAtPApdYYTtvRov/j5uCk1Oh5F+l2g0LXFOF907eViEz0E+t8D2CEljGcj6Z94dE9PoHEKSrxh6C8+7kPB+uTyIqUgMez60K18msNbSz1LXMq97K74N5XHIV0tE/CUogBScrdcgaQZo+oL/zFM7Y5QRwXx2HzehtuGuknd1krxaCJBDEPhXjTPbloq4X79tquyfHiGV6ZGNxhsG+fd7yYaco26B38fLWFY2olSwcpZKK7BAcPRff5GX+2vaEHaXwJQrX6Bw=
